### ISSUE TITLE
Wrong case in app.js

### ISSUE THREAD

**Issue by psxlover** [MediaBrowser/Emby.Web#154]
https://github.com/MediaBrowser/Emby.Web/blob/gh-pages/app.js#L446 should be connectionmanager, not connectionManager. 
I'd do a PR but I'm not sure if https://github.com/MediaBrowser/Emby.Web/blob/gh-pages/app.js#L162 should also be in lowercase.

**Comment by LukePulverenti** [comment]
why?

**Comment by psxlover** [comment]
Because the file https://github.com/MediaBrowser/Emby.Web/blob/gh-pages/apiclient/connectionmanager.js is in lowercase.

**Comment by psxlover** [comment]
I remember seeing an error about it. Since I can't reproduce it I'm closing this.
